from setuptools import setup, find_packages

setup(
    name="project-aether",
    version="0.1.0",
    author="Gabriel (Gabaoun) Penha",
    description="Advanced RAG Engine with Event-Driven Workflows",
    packages=find_packages(),
    install_requires=[
        "llama-index>=0.11.0",
        "llama-index-core",
        "llama-index-readers-file",
        "llama-index-embeddings-huggingface",
        "llama-index-llms-openai",
        "llama-index-postprocessor-flag-embedding-reranker",
        "llama-index-vector-stores-qdrant",
        "llama-index-vector-stores-postgres",
        "llama-index-utils-workflow",
        "pydantic>=2.0",
        "pydantic-settings",
        "qdrant-client",
        "redis",
        "psycopg2-binary",
        "pgvector",
        "ragas",
        "datasets",
        "pandas",
        "python-dotenv",
        "arize-phoenix",
        "presidio-analyzer",
        "presidio-anonymizer",
        "sentence-transformers",
        "FlagEmbedding",
        "tenacity",
        "numpy",
        "tiktoken",
        "fastapi",
        "uvicorn",
    ],
)
